/*
 * board.c
 *
 *  Created on: Apr 12, 2026
 *      Author: julius
 */

#include <stm32f091xc.h>

#include "utilities.h"


void init_board(void) {
    // Enable clocks
    RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
    RCC->AHBENR |= RCC_AHBENR_GPIOBEN;
    RCC->AHBENR |= RCC_AHBENR_GPIOCEN;

    // Configure outputs
    MODIFY_FIELD(GPIOA->MODER, GPIO_MODER_MODER9, ESF_GPIO_MODER_OUTPUT);   // STBY
    MODIFY_FIELD(GPIOC->MODER, GPIO_MODER_MODER7, ESF_GPIO_MODER_OUTPUT);   // AIN1
    MODIFY_FIELD(GPIOB->MODER, GPIO_MODER_MODER6, ESF_GPIO_MODER_OUTPUT);   // AIN2
    MODIFY_FIELD(GPIOA->MODER, GPIO_MODER_MODER7, ESF_GPIO_MODER_OUTPUT);   // PWMA
    MODIFY_FIELD(GPIOB->MODER, GPIO_MODER_MODER5, ESF_GPIO_MODER_OUTPUT);   // BIN1
    MODIFY_FIELD(GPIOB->MODER, GPIO_MODER_MODER3, ESF_GPIO_MODER_OUTPUT);   // BIN2
    MODIFY_FIELD(GPIOA->MODER, GPIO_MODER_MODER10, ESF_GPIO_MODER_OUTPUT);	// PWB

    // Safe initial states
    GPIOA->BSRR = GPIO_BSRR_BR_9;   // STBY low
    GPIOC->BSRR = GPIO_BSRR_BR_7;   // AIN1 low
    GPIOB->BSRR = GPIO_BSRR_BR_6;   // AIN2 low
    GPIOA->BSRR = GPIO_BSRR_BR_7;   // PWMA low
    GPIOB->BSRR = GPIO_BSRR_BR_5;   // BIN1 low
    GPIOB->BSRR = GPIO_BSRR_BR_3;   // BIN2 low
    GPIOA->BSRR = GPIO_BSRR_BR_10;  // PWMA low
}
