/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f091xc.h>

#include "debug.h"
#include "board.h"
#include "motor_control.h"


int main(void)
{
	/* You can use the Command Shell Console in STM32CubeIDE or an
	 * external program such as Putty or TeraTerm to view printf output.
	 * The settings are: Baud: 9600, Parity: None, Stop Bits: 1 with
	 * the ST-Link COM port setting.
	 * Clocks: Processor = 48 Mhz. AHB = 48 MHz. APB = 24 MHz.
	 */

    DBG_PRINTF("STARTING PROGRAM!\r\n");

    init_board();

    // Enable the motor controller TB6612
    GPIOA->BSRR = GPIO_BSRR_BS_9;	// STBY = 1


    while(1) {
		move_forward();
		delay_cycles(5000000);
		brake_stop();
		delay_cycles(5000000);
    }

}
