/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f091xc.h>
#include <string.h>

#include "debug.h"
#include "board.h"
#include "motor_control.h"
#include "usart.h"
#include "cbfifo.h"

static char cmd_buffer[QUEUE_SIZE] = {0};
static uint16_t buffer_index = 0;

static void print_hex(char cmd_buffer[]) {
	DBG_PRINTF("hex is: ");
	int  i = 0;
	while(cmd_buffer[i] != '\0') {
		DBG_PRINTF("%02x", (unsigned char) cmd_buffer[i]);
		i++;
	}
	DBG_PRINTF("\r\n");
}

int main(void)
{
	/*
	 * Clocks: Processor = 48 Mhz. AHB = 48 MHz. APB = 24 MHz.
	 */

    init_board();
    init_usart2();
    init_usart4();
    init_motor_control();


    DBG_PRINTF("STARTING PROGRAM\r\n");


    while(1) {
        if(bluetooth_try_getcommand(cmd_buffer, &buffer_index)) {
        	DBG_PRINTF("BT got: %s\r", cmd_buffer);
        	print_hex(cmd_buffer);
        	process_command(cmd_buffer);
        	buffer_index = 0;
        	memset(cmd_buffer, 0, QUEUE_SIZE);
        }


    }
}
